### PR TITLE
Sending Magic Packet after Trying to open already existing Stream.

### PR DESCRIPTION
**Pull request by DukeyAir**
I have found that sending the Magic Packet to the Goggles while they already stream it stops the Stream. So i put the Magic packet after the first try of a playback from an opened stream.

### CODE REVIEW

**Comment by sweebee** [comment]
This makes the app so much more reliable. will try a test flight in a couple of minutes.

**Comment by sweebee** [comment]
Did some flying. it did froze 1 time. But instant connection. Before I had to close the app and open it again to get it working.

Still slow frame rate but thats likely something else.

**Comment by jlucidar** [comment]
reviewing this ;)
Could you move this PR to the dev branch instead ?

**Comment by jlucidar** [comment]
oh neat ! checking this one right know !

**Comment by jlucidar** [comment]
hmmm, it seems that it breaks the "reconnect on deplug/plug" feature. is it just me ?

**Comment by sweebee** [comment]
reconnect on deplug/plug never worked for me (before this patch).

**Comment by jlucidar** [comment]
ok, it misses some commit that where pushed to dev yesterdaym, might be related to this.
I'm merging to dev and I will see if it helps.
Thanks for the PR !

**Pull request merged**
