### PR TITLE
First cut at centralizing device support info.

### PR DESCRIPTION
**Pull request by mavenius**
Should go into a db eventually, because curating markdown by hand is a pain.

This is related to #14, but I'm too dumb to figure out how to associate a PR to an issue.

### CODE REVIEW

**Comment by jlucidar** [comment]
Hey thanks for the PR ! will add a link in the readme as well :)

**Comment by mavenius** [comment]
Whoops; yeah, I meant to do that too :-) Thanks!

**Comment by squshy7** [comment]
can't we automate this from play store analytics?

**Comment by mavenius** [comment]
That's a great idea. Keeping up with the md fine would be a pain. I was
considering how to put this info into a db and building it dynamically, but
I'm not familiar enough with GH to know the best way to do it.

**Pull request merged**
