### PR TITLE
Splash Screens

### LINKED ISSUE #23: Splash Screens
As a Continuation of #21 - here's the assets and designs for splash screens & screens to show information while not streaming

Icons -> [goggles_icons.zip](https://github.com/fpvout/DigiView-Android/files/6481671/goggles_icons.zip)

Layout suggestions
demo screen - please connect goggles
demo screen - goggles disconnected
demo screen - connection lost

### PR DESCRIPTION
**Pull request by fmatt**
* resolves #23 by adding a splash screen and replacing toast messages with overlays
 DigiView screen transitions
* updated launcher icons to design from layout suggestion https://github.com/fpvout/DigiView-Android/issues/23#issue-892323468
launcher
* changed theme colors to match icons

### CODE REVIEW

**Comment by fichek** [comment]
Looking forward to trying this! 🙂

One note: I think we'll want to use the gradient launcher icon background that was in there.

icon

**Comment by fmatt** [comment]
Updated launcher icons:
ic_launcher
ic_launcher_round

**Review by jlucidar — APPROVED** [review]
Ha ! you were faster than me, I was just doing the same thing :p
btw it looks great !

**Comment by fichek** [comment]
@fmatt good job man, this looks so much better than the toasts! Are you on our Discord? Ping me there (same username) if you are, or you wanna [join](https://discord.gg/UH9jdPNbzK).

**Comment by jlucidar** [comment]
Merging this. it looks fantastic ! Thanks @fmatt :D

**Pull request merged**
